const inventoryData = [
  {
    id: '1',
    title: 'Organic Wheat Seeds',
    price: '₹250 / 5kg',
    location: 'Punjab',
    image: require('../assets/images/market1.png'),
    description: 'High-quality organic wheat seeds sourced from Punjab farms, ensuring robust growth and excellent yield.',
  },
  {
    id: '2',
    title: 'Steel Sickle',
    price: '₹150',
    location: 'Uttarakhand',
    image: require('../assets/images/market2.png'),
    description: 'Durable and sharp steel sickle perfect for harvesting crops and cutting through dense foliage efficiently.',
  },
  {
    id: '3',
    title: 'Pesticide Spray',
    price: '₹430',
    location: 'Haryana',
    image: require('../assets/images/market3.png'),
    description: 'Effective pesticide spray that protects crops from harmful insects and pests while being eco-friendly.',
  },
  {
    id: '4',
    title: 'Irrigation Motor',
    price: '₹3,999',
    location: 'Maharashtra',
    image: require('../assets/images/market4.png'),
    description: 'Powerful irrigation motor designed for efficient water pumping to support large-scale farming needs.',
  },
  {
    id: '5',
    title: 'Tractor Plough',
    price: '₹12,500',
    location: 'Rajasthan',
    image: require('../assets/images/market5.png'),
    description: 'Heavy-duty plough attachment for tractors, designed to break hard soil and prepare land for cultivation.',
  },
  {
    id: '6',
    title: 'Hybrid Rice Seeds',
    price: '₹600 / 10kg',
    location: 'West Bengal',
    image: require('../assets/images/market6.png'),
    description: 'High-yield hybrid rice seeds known for resistance to pests and diseases, suitable for all soil types.',
  },
  {
    id: '7',
    title: 'Drip Irrigation Kit',
    price: '₹2,200',
    location: 'Tamil Nadu',
    image: require('../assets/images/market7.png'),
    description: 'Complete drip irrigation kit for water-efficient farming, saving up to 70% water usage.',
  },
  {
    id: '8',
    title: 'Hand Hoe',
    price: '₹180',
    location: 'Bihar',
    image: require('../assets/images/market8.png'),
    description: 'Lightweight hand hoe made for weeding and soil loosening in small farms and gardens.',
  },
  {
    id: '9',
    title: 'Organic Fertilizer',
    price: '₹750 / 25kg',
    location: 'Madhya Pradesh',
    image: require('../assets/images/market9.png'),
    description: 'Eco-friendly organic fertilizer enriched with nutrients to promote soil health and crop growth.',
  },
  {
    id: '10',
    title: 'Mini Solar Pump',
    price: '₹6,500',
    location: 'Gujarat',
    image: require('../assets/images/market10.png'),
    description: 'Solar-powered water pump ideal for small farms, ensuring cost-effective irrigation solutions.',
  },
  {
    id: '11',
    title: 'Cotton Seeds',
    price: '₹1,050 / 2kg',
    location: 'Telangana',
    image: require('../assets/images/market11.png'),
    description: 'Premium cotton seeds with high germination rate, suitable for semi-arid and irrigated regions.',
  },
  {
    id: '12',
    title: 'Sprinkler Set',
    price: '₹3,200',
    location: 'Andhra Pradesh',
    image: require('../assets/images/market12.png'),
    description: 'High-efficiency sprinkler system that distributes water evenly across the field.',
  },
  {
    id: '13',
    title: 'Threshing Machine',
    price: '₹18,000',
    location: 'Uttar Pradesh',
    image: require('../assets/images/market13.png'),
    description: 'Compact threshing machine designed to separate grains efficiently from harvested crops.',
  },
  {
    id: '14',
    title: 'Cattle Feed',
    price: '₹950 / 25kg',
    location: 'Karnataka',
    image: require('../assets/images/market14.png'),
    description: 'Balanced cattle feed with essential nutrients to ensure better milk production and animal health.',
  },
  {
    id: '15',
    title: 'Organic Pesticide',
    price: '₹520',
    location: 'Odisha',
    image: require('../assets/images/market15.png'),
    description: 'Natural pesticide derived from neem and herbal extracts, safe for crops and soil.',
  },
  {
    id: '16',
    title: 'Farm Gloves',
    price: '₹120',
    location: 'Himachal Pradesh',
    image: require('../assets/images/market16.png'),
    description: 'Durable and comfortable gloves designed for long hours of farm work and crop handling.',
  },
  {
    id: '17',
    title: 'Solar Dryer',
    price: '₹4,500',
    location: 'Kerala',
    image: require('../assets/images/market17.png'),
    description: 'Solar-powered dryer designed for drying fruits, vegetables, and spices naturally and efficiently.',
  },
  {
    id: '18',
    title: 'Milking Machine',
    price: '₹9,800',
    location: 'Punjab',
    image: require('../assets/images/market18.png'),
    description: 'Portable milking machine for dairy farmers, ensuring hygienic and fast milking process.',
  },
  {
    id: '19',
    title: 'Sugarcane Seeds',
    price: '₹1,200 / 15kg',
    location: 'Uttar Pradesh',
    image: require('../assets/images/market19.png'),
    description: 'High-quality sugarcane seeds with excellent germination and high sugar yield.',
  },
  {
    id: '20',
    title: 'Plastic Water Tank',
    price: '₹7,300',
    location: 'Chhattisgarh',
    image: require('../assets/images/market20.png'),
    description: 'Strong and durable plastic water storage tank, suitable for farm and irrigation purposes.',
  },
];

export default inventoryData;
