const inventoryData = [
  {
    id: '1',
    title: 'Organic Wheat Seeds',
    price: '₹250 / 5kg',
    location: 'Punjab',
    category: 'Seeds',
    image: require('../assets/images/market1.png'),
    description: 'High-quality organic wheat seeds sourced from Punjab farms, ensuring robust growth and excellent yield.',
  },
  {
    id: '2',
    title: 'Steel Sickle',
    price: '₹150',
    location: 'Uttarakhand',
    category: 'Tools',
    image: require('../assets/images/market2.png'),
    description: 'Durable and sharp steel sickle perfect for harvesting crops and cutting through dense foliage efficiently.',
  },
  {
    id: '3',
    title: 'Pesticide Spray',
    price: '₹430',
    location: 'Haryana',
    category: 'Pesticides',
    image: require('../assets/images/market3.png'),
    description: 'Effective pesticide spray that protects crops from harmful insects and pests while being eco-friendly.',
  },
  {
    id: '4',
    title: 'Irrigation Motor',
    price: '₹3,999',
    location: 'Maharashtra',
    category: 'Machinery',
    image: require('../assets/images/market4.png'),
    description: 'Powerful irrigation motor designed for efficient water pumping to support large-scale farming needs.',
  },
  {
    id: '5',
    title: 'Tractor Plough',
    price: '₹12,500',
    location: 'Rajasthan',
    category: 'Machinery',
    image: require('../assets/images/market5.png'),
    description: 'Heavy-duty plough attachment for tractors, designed to break hard soil and prepare land for cultivation.',
  },
  {
    id: '6',
    title: 'Hybrid Rice Seeds',
    price: '₹600 / 10kg',
    location: 'West Bengal',
    category: 'Seeds',
    image: require('../assets/images/market6.png'),
    description: 'High-yield hybrid rice seeds known for resistance to pests and diseases, suitable for all soil types.',
  },
  {
    id: '7',
    title: 'Drip Irrigation Kit',
    price: '₹2,200',
    location: 'Tamil Nadu',
    category: 'Irrigation',
    image: require('../assets/images/market7.png'),
    description: 'Complete drip irrigation kit for water-efficient farming, saving up to 70% water usage.',
  },
  {
    id: '8',
    title: 'Hand Hoe',
    price: '₹180',
    location: 'Bihar',
    category: 'Tools',
    image: require('../assets/images/market8.png'),
    description: 'Lightweight hand hoe made for weeding and soil loosening in small farms and gardens.',
  },
  {
    id: '9',
    title: 'Organic Fertilizer',
    price: '₹750 / 25kg',
    location: 'Madhya Pradesh',
    category: 'Fertilizers',
    image: require('../assets/images/market9.png'),
    description: 'Eco-friendly organic fertilizer enriched with nutrients to promote soil health and crop growth.',
  },
  {
    id: '10',
    title: 'Mini Solar Pump',
    price: '₹6,500',
    location: 'Gujarat',
    category: 'Irrigation',
    image: require('../assets/images/market10.png'),
    description: 'Solar-powered water pump ideal for small farms, ensuring cost-effective irrigation solutions.',
  },
  {
    id: '11',
    title: 'Cotton Seeds',
    price: '₹1,050 / 2kg',
    location: 'Telangana',
    category: 'Seeds',
    image: require('../assets/images/market11.png'),
    description: 'Premium cotton seeds with high germination rate, suitable for semi-arid and irrigated regions.',
  },
  {
    id: '12',
    title: 'Sprinkler Set',
    price: '₹3,200',
    location: 'Andhra Pradesh',
    category: 'Irrigation',
    image: require('../assets/images/market12.png'),
    description: 'High-efficiency sprinkler system that distributes water evenly across the field.',
  },
  {
    id: '13',
    title: 'Threshing Machine',
    price: '₹18,000',
    location: 'Uttar Pradesh',
    category: 'Machinery',
    image: require('../assets/images/market13.png'),
    description: 'Compact threshing machine designed to separate grains efficiently from harvested crops.',
  },
  {
    id: '14',
    title: 'Cattle Feed',
    price: '₹950 / 25kg',
    location: 'Karnataka',
    category: 'Essentials',
    image: require('../assets/images/market14.png'),
    description: 'Balanced cattle feed with essential nutrients to ensure better milk production and animal health.',
  },
  {
    id: '15',
    title: 'Organic Pesticide',
    price: '₹520',
    location: 'Odisha',
    category: 'Pesticides',
    image: require('../assets/images/market15.png'),
    description: 'Natural pesticide derived from neem and herbal extracts, safe for crops and soil.',
  },
  {
    id: '16',
    title: 'Farm Gloves',
    price: '₹120',
    location: 'Himachal Pradesh',
    category: 'Essentials',
    image: require('../assets/images/market16.png'),
    description: 'Durable and comfortable gloves designed for long hours of farm work and crop handling.',
  },
  {
    id: '17',
    title: 'Solar Dryer',
    price: '₹4,500',
    location: 'Kerala',
    category: 'Machinery',
    image: require('../assets/images/market17.png'),
    description: 'Solar-powered dryer designed for drying fruits, vegetables, and spices naturally and efficiently.',
  },
  {
    id: '18',
    title: 'Milking Machine',
    price: '₹9,800',
    location: 'Punjab',
    category: 'Machinery',
    image: require('../assets/images/market18.png'),
    description: 'Portable milking machine for dairy farmers, ensuring hygienic and fast milking process.',
  },
  {
    id: '19',
    title: 'Sugarcane Seeds',
    price: '₹1,200 / 15kg',
    location: 'Uttar Pradesh',
    category: 'Seeds',
    image: require('../assets/images/market19.png'),
    description: 'High-quality sugarcane seeds with excellent germination and high sugar yield.',
  },
  {
    id: '20',
    title: 'Plastic Water Tank',
    price: '₹7,300',
    location: 'Chhattisgarh',
    category: 'Essentials',
    image: require('../assets/images/market20.png'),
    description: 'Strong and durable plastic water storage tank, suitable for farm and irrigation purposes.',
  },
  {
    id: '21',
    title: 'Tomato Seeds',
    price: '₹180 / 50g',
    location: 'Maharashtra',
    category: 'Seeds',
    image: require('../assets/images/market21.png'),
    description: 'High-yield hybrid tomato seeds with resistance to common plant diseases.',
  },
  {
    id: '22',
    title: 'Electric Sprayer',
    price: '₹2,500',
    location: 'Punjab',
    category: 'Machinery',
    image: require('../assets/images/market22.png'),
    description: 'Battery-powered sprayer for pesticides and fertilizers, reducing manual effort.',
  },
  {
    id: '23',
    title: 'Neem Oil Pesticide',
    price: '₹400 / 1L',
    location: 'Tamil Nadu',
    category: 'Pesticides',
    image: require('../assets/images/market23.png'),
    description: 'Organic neem oil extract used as a natural pesticide for protecting crops.',
  },
  {
    id: '24',
    title: 'Organic Compost',
    price: '₹600 / 20kg',
    location: 'Haryana',
    category: 'Fertilizers',
    image: require('../assets/images/market24.png'),
    description: 'Rich organic compost made from natural waste materials for healthy crop growth.',
  },
  {
    id: '25',
    title: 'Shovel',
    price: '₹300',
    location: 'Bihar',
    category: 'Tools',
    image: require('../assets/images/market25.png'),
    description: 'Strong steel shovel suitable for soil digging and farm work.',
  },
  {
    id: '26',
    title: 'PVC Pipes (Irrigation)',
    price: '₹2,000',
    location: 'Gujarat',
    category: 'Irrigation',
    image: require('../assets/images/market26.png'),
    description: 'Durable PVC pipes designed for agricultural irrigation systems.',
  },
  {
    id: '27',
    title: 'Maize Seeds',
    price: '₹450 / 5kg',
    location: 'Madhya Pradesh',
    category: 'Seeds',
    image: require('../assets/images/market27.png'),
    description: 'High-germination maize seeds with excellent yield potential.',
  },
  {
    id: '28',
    title: 'Safety Boots',
    price: '₹900',
    location: 'Uttarakhand',
    category: 'Essentials',
    image: require('../assets/images/market28.png'),
    description: 'Protective boots designed for safe farm work in muddy and rough terrains.',
  },
  {
    id: '29',
    title: 'Rice Thresher',
    price: '₹22,000',
    location: 'West Bengal',
    category: 'Machinery',
    image: require('../assets/images/market29.png'),
    description: 'Efficient rice threshing machine suitable for medium to large farms.',
  },
  {
    id: '30',
    title: 'Biofertilizer',
    price: '₹800 / 10kg',
    location: 'Andhra Pradesh',
    category: 'Fertilizers',
    image: require('../assets/images/market30.png'),
    description: 'Environment-friendly biofertilizer containing living microorganisms for soil health.',
  },
  {
    id: '31',
    title: 'Herbicide Spray',
    price: '₹600 / 1L',
    location: 'Rajasthan',
    category: 'Pesticides',
    image: require('../assets/images/market31.png'),
    description: 'Powerful herbicide spray for effective weed control in crop fields.',
  },
  {
    id: '32',
    title: 'Garden Rake',
    price: '₹250',
    location: 'Himachal Pradesh',
    category: 'Tools',
    image: require('../assets/images/market32.png'),
    description: 'Lightweight rake ideal for soil leveling, cleaning, and farm maintenance.',
  },
  {
    id: '33',
    title: 'Soybean Seeds',
    price: '₹500 / 5kg',
    location: 'Madhya Pradesh',
    category: 'Seeds',
    image: require('../assets/images/market33.png'),
    description: 'High-protein soybean seeds with excellent yield for farmers.',
  },
  {
    id: '34',
    title: 'Solar Insect Trap',
    price: '₹1,500',
    location: 'Odisha',
    category: 'Essentials',
    image: require('../assets/images/market34.png'),
    description: 'Solar-powered insect trap for protecting crops from harmful pests.',
  },
  {
    id: '35',
    title: 'Water Sprinkler Pump',
    price: '₹5,000',
    location: 'Kerala',
    category: 'Irrigation',
    image: require('../assets/images/market35.png'),
    description: 'Pump system designed for sprinkler irrigation in small to medium farms.',
  },
  {
    id: '36',
    title: 'Organic Manure',
    price: '₹700 / 25kg',
    location: 'Punjab',
    category: 'Fertilizers',
    image: require('../assets/images/market36.png'),
    description: 'Natural manure rich in nutrients for improving soil fertility.',
  },
  {
    id: '37',
    title: 'Weeding Tool',
    price: '₹200',
    location: 'Jharkhand',
    category: 'Tools',
    image: require('../assets/images/market37.png'),
    description: 'Easy-to-use hand tool for efficient weeding and soil aeration.',
  },
  {
    id: '38',
    title: 'Tractor Seeder',
    price: '₹15,000',
    location: 'Maharashtra',
    category: 'Machinery',
    image: require('../assets/images/market38.png'),
    description: 'Tractor-mounted seed drill for precise planting of seeds.',
  },
  {
    id: '39',
    title: 'Barley Seeds',
    price: '₹400 / 5kg',
    location: 'Haryana',
    category: 'Seeds',
    image: require('../assets/images/market39.png'),
    description: 'High-quality barley seeds with good resistance to common diseases.',
  },
  {
    id: '40',
    title: 'Protective Face Mask',
    price: '₹150',
    location: 'Delhi',
    category: 'Essentials',
    image: require('../assets/images/market40.png'),
    description: 'Reusable face mask for farmers to protect from dust and chemical sprays.',
  },
];

export default inventoryData;
